### ISSUE TITLE
Composer.json a bit too restrictive?

### ISSUE THREAD

**Issue by wernerkrauss** [guttmann/silverstripe-menumanager-subsites#1]
Hi, i'm just starting a project with subsites and menumanager, composer cannot install your package:

I'm using latest 

MenuManager 2.1.3
Framework 3.2.1
Subsites 1.1.0

which should in theory work with your code, but somehow your composer.json wants Menumanager 2.0, Framework 3.1 and Subsites 1.0

In theory the code of your module should work with SS 3.2...

**Comment by tyrannosaurusjames** [comment]
You're right it is a bit too restrictive, I'll give relaxing the version constraints a go when I get a chance (hopefully in the next day or two).

**Comment by tyrannosaurusjames** [comment]
@wernerkrauss have significantly relaxed the constraints in 1.0.1
